---
.travis.yml:
  secure_global_env:
    # PUBLISHER_PASSWORD
    - "Pcvzjth2c6X93y4oiEZkpdXxWunrJEdwOm+3jtr39K18istU7qCdAW1hwvM2qKHmNxKi4ZhC/GeLuJvClVhTjkk264Q+DWf7ArFAQ/GIw68O8mYzYlYr06qVLT1JsXbxiPVvg4QIWKL9g1e1NL04r9SzT0qV8XBDOPgWFjV5gJw="
